/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookshop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author matvey
 */





public class Biling extends javax.swing.JFrame {

    /**
     * Creates new form Biling
     */
    public Biling() {
        initComponents();
        displayBooks();
        BookTitleTb.setEditable(false);
        PriceTb.setEditable(false);
        countRow();
          BillIdTb.setEditable(false);
    }
    public Biling(String Uname)
    {
          initComponents();
          UNameLbl.setText(Uname);
          displayBooks();
          BookTitleTb.setEditable(false);
          PriceTb.setEditable(false);
           countRow();
           BillIdTb.setEditable(false);
           
          
    }
    
    
    
     Connection Con=null;
    Statement St=null;
    ResultSet Rs=null;
    
    private void displayBooks()
    { 
        try
        {
               Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root","1234");
               St=Con.createStatement();
               Rs=St.executeQuery("select * from bookshop.booktbl");
               BooksTable.setModel(DbUtils.resultSetToTableModel(Rs));
              
        }
        catch(Exception e)
                {
                    e.printStackTrace();
                }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        BookTitleTb = new javax.swing.JTextField();
        QuanityTb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ClientNameTb = new javax.swing.JTextField();
        PriceTb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PrintBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BooksTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        FinalLb = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JLabel();
        AddToBillBtn = new javax.swing.JButton();
        BillIdTb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        UNameLbl = new javax.swing.JLabel();
        ResBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Book Title");

        BookTitleTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTitleTbActionPerformed(evt);
            }
        });

        QuanityTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanityTbActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Quanity");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Client Name");

        ClientNameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientNameTbActionPerformed(evt);
            }
        });

        PriceTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTbActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Price");

        PrintBtn.setText("Print");
        PrintBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintBtnMouseClicked(evt);
            }
        });
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        BooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Title", "Author", "Cathegory", "Quanity", "Price"
            }
        ));
        BooksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BooksTable);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Books List");

        BillTxt.setColumns(20);
        BillTxt.setRows(5);
        jScrollPane2.setViewportView(BillTxt);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Bill");

        FinalLb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        FinalLb.setText("Total");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\каво\\Desktop\\C2kjxxwXUAEYktB.png")); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        LogoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\каво\\Desktop\\назад.png")); // NOI18N
        LogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseClicked(evt);
            }
        });

        AddToBillBtn.setText("Add to Bill");
        AddToBillBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddToBillBtnMouseClicked(evt);
            }
        });
        AddToBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToBillBtnActionPerformed(evt);
            }
        });

        BillIdTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillIdTbActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Bill Number");

        UNameLbl.setText("UName");

        ResBtn.setText("Reset");
        ResBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Book Shop Managment System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClientNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(BookTitleTb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PriceTb, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuanityTb, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BillIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AddToBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoutBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(ResBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(FinalLb))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 319, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(UNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(FinalLb)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrintBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(ResBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BookTitleTb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuanityTb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(BillIdTb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddToBillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ClientNameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PriceTb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BookTitleTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTitleTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookTitleTbActionPerformed

    private void QuanityTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanityTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuanityTbActionPerformed

    private void ClientNameTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNameTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientNameTbActionPerformed

    private void PriceTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTbActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void LogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnMouseClicked
int stock=0;
 int BId;
    private void BooksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksTableMouseClicked
           DefaultTableModel model=(DefaultTableModel)BooksTable.getModel();
           
      int index=BooksTable.getSelectedRow();
      
       BookTitleTb.setText(model.getValueAt(index,1).toString());
       stock=Integer.valueOf(model.getValueAt(index,4).toString());
       PriceTb.setText(model.getValueAt(index,5).toString());
       BId=Integer.valueOf(model.getValueAt(index,0).toString());
    }//GEN-LAST:event_BooksTableMouseClicked

    private void AddToBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToBillBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddToBillBtnActionPerformed

    
    int i=0;
    int total=0;
    int finalPrice;
    private void AddToBillBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddToBillBtnMouseClicked
        
        if(QuanityTb.getText().isEmpty()||BookTitleTb.getText().isEmpty())
        {
            
              JOptionPane.showMessageDialog(this,"Missing info");
        }
        
        
        else if (Integer.valueOf(QuanityTb.getText())>stock)
        {
              JOptionPane.showMessageDialog(this,"Not enough books in stock");
                  
        }
        else if(Integer.valueOf(QuanityTb.getText())<=0)
        {
             JOptionPane.showMessageDialog(this,"Quanity must be more than 0");
        }
        
        
        else
        {
            i++;
            
            total=Integer.valueOf(QuanityTb.getText())*Integer.valueOf(PriceTb.getText());
                    
            
            if (i==1)
            {
                BillTxt.setText( BillTxt.getText()+"        ===============BOOK SHOP===============\n"+"NUM     PRODUCT       PRICE     QUANITY     TOTAL\n"+i+"                "+BookTitleTb.getText()+"           "+QuanityTb.getText()+"               "+PriceTb.getText()+"                "+total+"\n");
                            
            }
            else
            {
                BillTxt.setText( BillTxt.getText()+i+"                "+BookTitleTb.getText()+"            "+QuanityTb.getText()+"              "+PriceTb.getText()+"                "+total+"\n");
            }
            finalPrice=finalPrice+total;
            FinalLb.setText(finalPrice+"$");
            updateBookStock();
            reset();
        }    
            
    }//GEN-LAST:event_AddToBillBtnMouseClicked

    
       Statement St1=null;
    ResultSet Rs1=null;
    private void countRow()
    {
        try
        {

              Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root","1234");
               St1=Con.createStatement();
               Rs1=St1.executeQuery("select * from bookshop.billtbl order by BNUM DESC FETCH FIRST 1 ROWS ONLY");
            Rs1.next();
            int id=Rs1.getInt(1)+1;
            BillIdTb.setText(id+"");
            
        }
catch(Exception e)
{
    e.printStackTrace();
}
        
    
    }
    
    
    
    
    
   
    
   private void updateBookStock()
   {
    
         try
                    {
                        
                        
                        Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root","1234");
                   int newQty=stock-Integer.valueOf(QuanityTb.getText());
                      String Query="Update bookshop.booktbl set Quanity="+newQty+" where BId="+BId;
                      Statement Delete =Con.createStatement();
                      Delete.executeUpdate(Query);
                       
                         JOptionPane.showMessageDialog(this,"Book added");
                         displayBooks();
                         reset();
                         Con.close();
                      
                    } catch(Exception e)
                    {
                    e.printStackTrace();
                    }
       
       
   }
    
    private void reset()
    {
        BookTitleTb.setText("");
        PriceTb.setText("");
        QuanityTb.setText("");
       // ClientNameTb.setText("");
       

        
        
        
    }
    
    public void saveBill()
    {
                        BillIdTb.setText("2");                    
        if (BillIdTb.getText().isEmpty()||  ClientNameTb.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Missing info");
        }
            else{
                 try
                    {
                        
                        
                        Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bookshop","root","1234");
                        PreparedStatement add=Con.prepareStatement("insert into billtbl values(?,?,?,?)");
                        add.setInt(1, Integer.valueOf(BillIdTb.getText()));
                        add.setString(2,UNameLbl.getText());
                        add.setString(3,ClientNameTb.getText());                      
                        add.setInt(4,Integer.valueOf(total));
                     
                         
                         int row=add.executeUpdate();
                         JOptionPane.showMessageDialog(this,"Bill saved");
                       
                     
                    } catch(Exception e)
                    {
                    e.printStackTrace();
                    }
                    
        }
    } 
    
    
    
    
    private void PrintBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintBtnMouseClicked
     try
     {
         BillTxt.print();
         saveBill();
         reset();
          BillTxt.setText("");
         i=0;
         FinalLb.setText("Total");
         
     } catch(Exception e)
     {
         e.printStackTrace();
    }//GEN-LAST:event_PrintBtnMouseClicked

    private void BillIdTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillIdTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillIdTbActionPerformed

    private void ResBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResBtnMouseClicked
       reset();
    }//GEN-LAST:event_ResBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToBillBtn;
    private javax.swing.JTextField BillIdTb;
    private javax.swing.JTextArea BillTxt;
    private javax.swing.JTextField BookTitleTb;
    private javax.swing.JTable BooksTable;
    private javax.swing.JTextField ClientNameTb;
    private javax.swing.JLabel FinalLb;
    private javax.swing.JLabel LogoutBtn;
    private javax.swing.JTextField PriceTb;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTextField QuanityTb;
    private javax.swing.JButton ResBtn;
    private javax.swing.JLabel UNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
